/**
* @author cornek
* @since 1.0
* @version 1.2.5
*/

var mapIcons={};var enquiryEventData={};var unitInfoBox=null;var unitEnquiryModal=null;function dataTablePriceRenderer(data,type,full){return jQuery.formatNumber(data,{format:"#,###",locale:"us"});}
function dataTableStatusRenderer(data,type,full){return'<i title="'+data+'" class="pe-sale-status pe-status-'+full.get("systemStatus")+' icon-stop"></i>&nbsp<span class="hidden-phone">'+data+'</span>';}
function instanceLabelLinkRenderer(data,type,row){return data}
function enquireRender(data,type,full){return'<a href="#" class="btn btn-small pe-contact-button btn-success" data-unit-key="'+data+'" data-unit-label="'+full.label+'"><i class="icon-envelope"></i><span class="hidden-phone">&nbsp;Enquire</span></a>';}
function closeInfoBox(){if(window.unitInfoBox!=null){window.unitInfoBox.hide();}
    enquiryEventData={};return false;}
function openEnquireModalOnClick(id,unitLabel,unitKey){enquiryEventData={'id':id,'unitLabel':unitLabel,'unitKey':unitKey};openEnquireModal(PELiveList[id].settings.enquiryMsg.replace("{UNIT}",unitLabel));return false;}
function openEnquireModal(msg){if(unitEnquiryModal==null){unitEnquiryModal=jQuery('.pe-modal-plugin');unitEnquiryModal.on('hide',function(){jQuery(".modal-backdrop").remove();});}
    unitEnquiryModal.find("textarea").html(msg);unitEnquiryModal.find(".pe-input-firstname").focus();unitEnquiryModal.modal('show').addClass("in").show();}
function closeEnquiryModal(){unitEnquiryModal.modal('hide');}
function submitUnitEnquiry(buttonObj){jQuery(buttonObj).button('loading');var $form=jQuery(buttonObj).closest('form');var formData=($form.serializeArray());var postData={domain:window.location.hostname,unitsOfInterest:enquiryEventData.unitKey};jQuery.each(formData,function(key,val){postData[val.name]=val.value;});jQuery.ajax({url:PELiveList[enquiryEventData.id].settings.peLeadURL+"/api/v2/"+PELiveList[enquiryEventData.id].settings.authenticationCode+"/liveList/"+PELiveList[enquiryEventData.id].settings.remoteKey+"/newContact",dataType:"jsonp",data:postData,jsonpCallback:"peNewContact",success:function(data){if(data.result=="success"){closeEnquiryModal();}else{alert("Error while submitting this request");}
    jQuery(buttonObj).button('reset');}});return false;}
function success(){}
function invalid(){}
function visible(id,columnLabel){if(PELiveList[id].settings.hideColumns==undefined){return true}
    return!(PELiveList[id].settings.hideColumns.indexOf(columnLabel)>-1)}
function launchPrinterFriendly(){var w=window.open('');w.document.write("<html><head>");var bootstrap=jQuery("#bootstrap").attr('href');var stylesheet=jQuery("#livelist-styles").attr('href');w.document.write("<link href='"+bootstrap+"' type='text/css' rel='stylesheet' media='screen,print' />");w.document.write("<link href='"+stylesheet+"' type='text/css' rel='stylesheet' media='screen,print' />");w.document.write("<title>Unit List of XYZ</title></head><body id='print-friendly'>");w.document.write("<h1>Unit List of XYZ</h1>");w.document.write(jQuery('table#DataTables_Table_0').parent().html());w.document.write('</body></html>');w.document.close();}
var PELiveListUnit=Backbone.Model.extend({googleMapMarker:null,dataTableRow:null,map:null,dataTable:null,initialize:function(){this.bind('change:matchedSearchFilter',this.updateModel);},updateModel:function(){var self=this;if(self.googleMapMarker!=null&&self.map!=null){if(!self.get('matchedSearchFilter')&&self.googleMapMarker.map!=null){self.googleMapMarker.setMap(null);}
else if(self.get('matchedSearchFilter')&&self.googleMapMarker.map==null){self.googleMapMarker.setMap(self.map);}}}});var PELiveListUnitCollection=Backbone.Collection.extend({instanceId:"default",unitsPriceRange:[0,0],unitsMapBounds:null,filteredPriceRange:[],filteredFloors:null,filterTimeout:null,filterBufferFlag:true,initialize:function(){var self=this;_.each(this.models,function(model){if(model.get('systemStatus').toLowerCase()!="sold"&&parseInt(model.get('priceLow'))!=0){if(self.unitsPriceRange[0]==0||parseInt(model.get('priceLow'))<self.unitsPriceRange[0]){self.unitsPriceRange[0]=parseInt(model.get('priceLow'));}
    if(parseInt(model.get('priceLow'))>self.unitsPriceRange[1]){self.unitsPriceRange[1]=parseInt(model.get('priceLow'));}}
    if(model.get('lat')!=null&&model.get('lng')!=null){var position=new google.maps.LatLng(model.get('lat'),model.get('lng'));if(self.unitsMapBounds==null){self.unitsMapBounds=new google.maps.LatLngBounds();}
        self.unitsMapBounds.extend(position)}});self.unitsPriceRange[0]=Math.floor(self.unitsPriceRange[0]/1000)*1000;self.unitsPriceRange[1]=Math.ceil(self.unitsPriceRange[1]/1000)*1000;self.filteredPriceRange=self.unitsPriceRange;return true},add:function(newUnit){if(newUnit.get('systemStatus')==""||newUnit.get('systemStatus')==undefined){newUnit.set('systemStatus',newUnit.get('saleStatus').toLowerCase());}
    if(PELiveList[this.instanceId].settings==undefined||PELiveList[this.instanceId].settings.showStatus.indexOf(newUnit.get('systemStatus'))>-1){Backbone.Collection.prototype.add.call(this,newUnit);}},filterBuffer:function(){this.filterBufferFlag=false;this.filterTimeout=null;this.filterViaSearch();},filterViaSearch:function(){var instance=this;if(!this.filterBufferFlag){this.filterBufferFlag=true;var statusList=[];var selectedStatusList=jQuery(".status-input input[name='status']:checked");jQuery.each(selectedStatusList,function(key,val){statusList.push(jQuery(val).val());});instance.filterData(instance.filteredPriceRange,statusList,instance.filteredFloors);}else{if(instance.filterTimeout!=null){window.clearTimeout(this.filterTimeout);}
    instance.filterTimeout=setTimeout(function(){instance.filterBuffer()},200);}},filterData:function(priceRange,statusList,floor){_.each(this.models,function(model){var matchedSearch=true;if(model.get('systemStatus').toLowerCase()!="sold"&&parseInt(model.get('priceLow'))!=0){matchedSearch=(model.get('priceLow')>=priceRange[0]&&model.get('priceLow')<=priceRange[1]);}
    if(matchedSearch&&floor!=null&&floor!="none"){matchedSearch=(model.get("floor")==floor);}
    if(matchedSearch){matchedSearch=statusList.length==0||statusList.length==3||_.contains(statusList,model.get('systemStatus'));}
    model.set('matchedSearchFilter',matchedSearch);});closeInfoBox();this.trigger('filter');}});var LiveListView=Backbone.View.extend({dataTable:null,tableBody:null,visible:false,initialize:function(){this.collection.bind('filter',this.collectionUpdate,this);this.collection.bind('highlightRow',this.highlightRow,this);},render:function(){},show:function(){this.visible=true;this.$el.show();this.collectionUpdate();},hide:function(){this.visible=false;this.$el.hide();},collectionUpdate:function(){if(this.visible&&this.dataTable!=null){this.dataTable.fnReloadAjax();}},highlightRow:function(unit){}});var LiveMapView=Backbone.View.extend({map:null,firstLoad:true,markerBounds:null,polyline:[],phaseData:[],instanceId:null,initialize:function(){this.collection.bind('filter',this.collectionUpdate,this);},initializeMap:function(){var myOptions={disableAutoPan:false,maxWidth:200,pixelOffset:new google.maps.Size(-248,-20),zIndex:null,boxStyle:{opacity:1,position:"relative",width:"248px"},closeBoxURL:"",infoBoxClearance:new google.maps.Size(1,1),isHidden:false,pane:"floatPane",enableEventPropagation:false};window.unitInfoBox=new InfoBox(myOptions);var livelistMapView=this;if(livelistMapView.markerBounds==null){livelistMapView.destroy();}else{var mapOptions={zoom:4,center:livelistMapView.markerBounds.getCenter(),mapTypeId:google.maps.MapTypeId.ROADMAP};livelistMapView.map=new google.maps.Map(livelistMapView.$el.get(0),mapOptions);livelistMapView.render();livelistMapView.map.fitBounds(livelistMapView.markerBounds);if(PELiveList[livelistMapView.instanceId].polydata!=null){var multiData=PELiveList[livelistMapView.instanceId].polydata.split("|");jQuery.each(multiData,function(key,dataLine){var mvcArray=generateMVCArray(dataLine)
    livelistMapView.polyline.push(new google.maps.Polyline({map:livelistMapView.map,path:mvcArray}));});}
    if(PELiveList[livelistMapView.instanceId].phaseData!=null){jQuery.each(PELiveList[livelistMapView.instanceId].phaseData,function(key,phase){var phaseObj={}
        var mvcArray=generateMVCArray(phase.points)
        phaseObj.outline=new google.maps.Polyline({map:livelistMapView.map,path:mvcArray});var labelText=phase.name;var myOptions={content:labelText,boxStyle:{border:"0px solid black",textAlign:"center",fontSize:"15pt",fontWeight:"bold",width:"100px"},disableAutoPan:true,pixelOffset:new google.maps.Size(-25,0),position:new google.maps.LatLng(phase.lat,phase.lng),closeBoxURL:"",isHidden:false,pane:"mapPane",enableEventPropagation:true};var ibLabel=new InfoBox(myOptions);ibLabel.open(livelistMapView.map);phaseObj.label=ibLabel;livelistMapView.phaseData.push(phaseObj);})}
    google.maps.event.addListener(livelistMapView.map,"click",function(event){return closeInfoBox();});}},render:function(){var self=this;self.collection.each(function(unit){if(unit.get('lat')!=null&&unit.get('lng')!=null){var image={url:mapIcons[unit.get('systemStatus')],size:new google.maps.Size(12,12),origin:new google.maps.Point(0,0),anchor:new google.maps.Point(6,6)};unit.map=self.map;unit.googleMapMarker=new google.maps.Marker({map:self.map,position:new google.maps.LatLng(unit.get('lat'),unit.get('lng')),icon:image,unit:unit});google.maps.event.addListener(unit.googleMapMarker,"click",function(event){var filteredUnitModel={};var unitJSON=unit.toJSON();jQuery.each(mapAttribute,function(key,val){if(!(key=="priceLow"&&unitJSON.systemStatus=="sold")){if(_.has(unitJSON,key)&&visible(self.instanceId,key)){var value=val.render!=null?val.render(unitJSON[key],{currency:PELiveList[self.instanceId].settings.currency}):unitJSON[key];filteredUnitModel[key]={value:value,title:val.title}}}});var model={instanceId:self.collection.instanceId,unit:filteredUnitModel};window.unitInfoBox.setContent("<div class='pe-unit-info'>"+jQuery("#unit-balloon-template").tmpl(model).html()+"</div>");window.unitInfoBox.show();window.unitInfoBox.open(self.map,this);});}});return this;},show:function(){this.$el.show();google.maps.event.trigger(this.map,"resize");if(this.firstLoad){this.map.fitBounds(this.markerBounds);this.firstLoad=false;}
    if(jQuery("#"+this.instanceId+' .floor-search').is(":visible")){var $select=jQuery("#"+this.instanceId+' select.floor-selector');$select.find('option[value="none"]').hide();if($select.find('option:eq(0)').attr("selected")=="selected"){$select.find('option:eq(1)').attr('selected','selected');}
        PELiveList[this.instanceId].units.filteredFloors=$select.val();this.collection.filterViaSearch();}
    jQuery('#'+this.instanceId+' .view-toggle .btn.active').removeClass("active");jQuery('#'+this.instanceId+' .view-toggle .btn[data-toggle="map"]').addClass("active");},hide:function(){this.$el.hide();jQuery("#"+this.instanceId+' select.floor-selector').find('option[value="none"]').show();closeInfoBox();},destroy:function(){this.hide();this.$el.closest(".pe-plugins").find(".view-toggle").hide();},collectionUpdate:function(){}});jQuery.extend(jQuery.fn.dataTableExt.oStdClasses,{"sSortAsc":"header headerSortDown","sSortDesc":"header headerSortUp","sSortDisabled":"header headerSortDisabled","sSortable":"header"});jQuery.fn.dataTableExt.oSort['numeric-comma-pre']=function(a){var x=(a=="-")?0:a.replace(/[^0-9]/g,"");return parseFloat(x);};jQuery.fn.dataTableExt.oSort['numeric-comma-asc']=function(x,y){return((x<y)?-1:((x>y)?1:0));};jQuery.fn.dataTableExt.oSort['numeric-comma-desc']=function(x,y){return((x<y)?1:((x>y)?-1:0));};jQuery.fn.dataTableExt.oApi.fnReloadAjax=function(oSettings,sNewSource,fnCallback,bStandingRedraw){if(typeof sNewSource!='undefined'&&sNewSource!=null){oSettings.sAjaxSource=sNewSource;}
    this.oApi._fnProcessingDisplay(oSettings,true);var that=this;var iStart=oSettings._iDisplayStart;var aData=[];this.oApi._fnServerParams(oSettings,aData);oSettings.fnServerData(oSettings.sAjaxSource,aData,function(json){that.oApi._fnClearTable(oSettings);var aData=(oSettings.sAjaxDataProp!=="")?that.oApi._fnGetObjectDataFn(oSettings.sAjaxDataProp)(json):json;for(var i=0;i<aData.length;i++){if(aData[i].matchedSearchFilter){var row=that.oApi._fnAddData(oSettings,aData[i]);}}
        oSettings.aiDisplay=oSettings.aiDisplayMaster.slice();that.fnDraw();if(typeof bStandingRedraw!='undefined'&&bStandingRedraw===true){oSettings._iDisplayStart=iStart;that.fnDraw(false);}
        that.oApi._fnProcessingDisplay(oSettings,false);if(typeof fnCallback=='function'&&fnCallback!=null){fnCallback(oSettings);}},oSettings);};window.PELiveList={};function initLiveList(id,settings){var listSettings=settings||{};listSettings.showStatus=settings.showStatus||'available,unreleased,under-offer,sold';listSettings.view=settings.view||"all";var startViewDefault=settings.view=="all"?"list":settings.view;listSettings.startView=settings.startView||startViewDefault;listSettings.currency=settings.currency||"$";listSettings.height=settings.height||500;listSettings.remoteKey=settings.remoteKey||"TESTKEY";listSettings.authenticationCode=settings.authenticationCode.replace(/-/g,"")||"TESTCODE";listSettings.enquiryMsg=settings.enquiryMsg||"I'm interested in Unit {UNIT}. Please send me more information";listSettings.waitingListMsg=settings.enquiryMsg||"Please put me on the waiting list for Unit {UNIT}";PELiveList[id]={};PELiveList[id].settings=listSettings;PELiveList[id].units=new PELiveListUnitCollection();PELiveList[id].units.instanceId=id;PELiveList[id].polydata=null;PELiveList[id].destroyed=false;PELiveList[id].phaseData=null;PELiveList[id].loadingCurrent=0;PELiveList[id].loadingTotal=null;PELiveList[id].loadingData=[];PELiveList[id].loadingPanel=jQuery("#"+id+" .pe-loading-overlay");notifyServer(id);dataTablePriceRenderer=function(data,type,row){if(row.systemStatus=="sold"){return"-";}else{return priceRenderer(data,{currency:PELiveList[id].settings.currency});}};dataTableStatusRenderer=function(data,type,row){return'<i title="'+data+'" class="pe-sale-status pe-status-'+row.systemStatus+' icon-stop"></i>&nbsp<span class="hidden-phone">'+data+'</span>';};instanceLabelLinkRenderer=function(data,type,row){return data;};mapIcons['sold']=PELiveList[id].settings.imageRoot+"status-sold-sml.png";mapIcons['under-offer']=PELiveList[id].settings.imageRoot+"status-under-offer-sml.png";mapIcons['available']=PELiveList[id].settings.imageRoot+"status-available-sml.png";mapIcons['unreleased']=PELiveList[id].settings.imageRoot+"status-unreleased-sml.png";PELiveList[id].interval=setInterval(function(){processLoadedData(id)},100);jQuery.ajax({url:PELiveList[id].settings.remoteDataURL+PELiveList[id].settings.remoteKey+"/livelist-units.json",dataType:"jsonp",jsonpCallback:"peData_"+PELiveList[id].settings.remoteKey,success:function(data){PELiveList[id].polydata=data.points;PELiveList[id].phaseData=data.phases;PELiveList[id].settings.currency=data.config.currency;PELiveList[id].settings.columnConfig=data.config.columns;PELiveList[id].settings.floorSelector=data.config.floorSelector||false;if(PELiveList[id].settings.floorSelector==false){jQuery("#"+id+" .floor-search").hide();}else{var $floorSelector=jQuery("#"+id+" .floor-search").find("select.floor-selector");var floors=PELiveList[id].settings.floorSelector.split(/,/g);jQuery.each(floors,function(key,val){$floorSelector.append("<option value=\""+val+"\">"+val+"</option>");});}
    PELiveList[id].loadingTotal=data.data.length;setLoadingProgress(id,PELiveList[id].loadingTotal,10);jQuery.each(data.data,function(index,unitData){var unit={};PELiveList[id].loadingData.push(unitData)});}});}
function notifyServer(id){var authenticationData={domain:window.location.hostname};jQuery.ajax({url:PELiveList[id].settings.peLeadURL+"/api/v2/"+PELiveList[id].settings.authenticationCode+"/liveList/"+PELiveList[id].settings.remoteKey+"/authorise",dataType:"jsonp",data:authenticationData,jsonpCallback:"peAuthorize",success:function(data){if(data.result&&data.result==="fail"){jQuery(".pe-live-list").remove();PELiveList[id].destroyed=true;}}});}
function setLoadingProgress(id,total,loaded){PELiveList[id].loadingPanel.find(".bar").css("width",(loaded/total)*100)}
function hideLoadingProgress(id){PELiveList[id].loadingPanel.fadeOut();}
function generateMVCArray(dataLine){var mvcArray=new google.maps.MVCArray();var dataPoints=dataLine.split(" ");jQuery.each(dataPoints,function(key,val){var tmpLatLng=val.split(",")
    mvcArray.push(new google.maps.LatLng(tmpLatLng[1],tmpLatLng[0]))});mvcArray.push(mvcArray.getAt(0))
    return mvcArray}
function processLoadedData(id){var batchSize=(PELiveList[id].loadingData.length>100)?100:PELiveList[id].loadingData.length;if(PELiveList[id].destroyed===true){clearInterval(PELiveList[id].interval);hideLoadingProgress(id);return}
    if(PELiveList[id].loadingData.length>0){for(i=0;i<=batchSize;i++){var unitData=PELiveList[id].loadingData.pop();if(unitData!=undefined){var unit={};_.each(PELiveList[id].settings.columnConfig,function(key,num){unit[key]=unitData[num];});unit['matchedSearchFilter']=true;PELiveList[id].units.add(new PELiveListUnit(unit));PELiveList[id].loadingCurrent++;setLoadingProgress(id,PELiveList[id].loadingTotal,PELiveList[id].loadingCurrent);}}}
    if(PELiveList[id].loadingCurrent==PELiveList[id].loadingTotal&&PELiveList[id].loadingData.length==0){clearInterval(PELiveList[id].interval);hideLoadingProgress(id);initLiveListInterface(id);}}
function initLiveListInterface(id){jQuery('.pe-contact-button').live('click',function(e){e.preventDefault();var unitLabel=jQuery(this).data('unit-label');var unitKey=jQuery(this).data('unit-key');enquiryEventData={'id':id,'unitLabel':unitLabel,'unitKey':unitKey};openEnquireModal(PELiveList[id].settings.enquiryMsg.replace("{UNIT}",unitLabel));});var liveListTable;var liveListMap;var propertyEngineTable=jQuery('#'+id+' .property-engine-table');var dtColumns=[];_.each(PELiveList[id].settings.columnConfig,function(val,num){if(_.has(columnAttributes,val)){var fnRender=columnAttributes[val].render;if(columnAttributes[val].title=="Status"){fnRender=dataTableStatusRenderer;}else if(columnAttributes[val].type=="numeric-comma"){fnRender=dataTablePriceRenderer;}else if(fnRender==labelLinkRenderer){fnRender=instanceLabelLinkRenderer;}
    dtColumns.push({"sTitle":columnAttributes[val].title,"mDataProp":val,"bVisible":visible(id,val),mRender:fnRender,sType:columnAttributes[val].type})}});dtColumns.push({"sTitle":"","mDataProp":"remoteKey","bVisible":visible(id,"enquire"),"bSearchable":false,"bSortable":false,mRender:enquireRender});if(PELiveList[id].settings.view=='list'||PELiveList[id].settings.view=='all'){liveListTable=new LiveListView({collection:PELiveList[id].units,el:propertyEngineTable});liveListTable.tableBody=jQuery('#'+id+' .livelist-table tbody');liveListTable.dataTable=jQuery('#'+id+' .livelist-table').dataTable({"bPaginate":false,"bFilter":true,"sDom":'t',"sScrollY":PELiveList[id].settings.height+"px","bAutoWidth":true,"bInfo":false,"aaSorting":[[0,"asc"]],"aoColumns":dtColumns,sAjaxSource:"",sAjaxDataProp:"",fnServerData:function(sSource,aoData,fnCallback){fnCallback(PELiveList[id].units.toJSON());}});liveListTable.render();liveListTable.show();if(PELiveList[id].settings.startView!='list'){liveListTable.hide();}}
    PELiveList[id].units.initialize();var priceRange=PELiveList[id].units.unitsPriceRange;var unitsMapBounds=PELiveList[id].units.unitsMapBounds;liveListMap=new LiveMapView({collection:PELiveList[id].units,el:jQuery('#'+id+' .property-engine-map-canvas')});liveListMap.instanceId=id;if(PELiveList[id].settings.view=='map'||PELiveList[id].settings.view=='all'){if(PELiveList[id].settings.view=='map'){propertyEngineTable.closest(".pe-plugins").find(".view-toggle").hide();}
        liveListMap.markerBounds=unitsMapBounds;liveListMap.initializeMap();}
    if(PELiveList[id].settings.view=='all'&&PELiveList[id].settings.startView!='map'){liveListMap.hide();}
    if(PELiveList[id].settings.view=='list'){liveListMap.destroy();}
    if(PELiveList[id].settings.startView=='map'){liveListMap.show();}
    jQuery('#'+id+" .status-filter").on('click',".btn",function(){var checkbox=jQuery('#'+id+" .status-input input[value='"+jQuery(this).val()+"']");checkbox.attr("checked",!checkbox.attr("checked"));PELiveList[id].units.filterViaSearch();});jQuery('#'+id+" select.floor-selector").change(function(){PELiveList[id].units.filteredFloors=jQuery(this).val();PELiveList[id].units.filterViaSearch();});jQuery('#'+id+" .price-search .amount").slider({from:priceRange[0],to:priceRange[1],step:1000,smooth:true,round:4,limits:true,dimension:"&nbsp;"+PELiveList[id].settings.currency,skin:"round_plastic",format:"#,###",locale:"us",onstatechange:function(data){var minMax=data.split(";");var minValue=minMax[0];var maxValue=minMax[1];PELiveList[id].units.filteredPriceRange=[minValue,maxValue];PELiveList[id].units.filterViaSearch();}}).slider("value",priceRange[0],priceRange[1]);jQuery('#'+id+' .view-toggle .btn').click(function(){if(!jQuery(this).hasClass('active')){if(jQuery(this).data('toggle')=='map'){if(liveListTable!=null){liveListTable.hide();}
        liveListMap.show();}else{if(liveListMap!=null){liveListMap.hide();}
        liveListTable.show();}
        jQuery('#'+id+' .view-toggle > .btn.active').removeClass('active');jQuery(this).addClass('active')}});}